 Tue, 03 Mar 2020 23:17:20  INFO logger.py <module> [ line:20 ] hehehehe
 Tue, 03 Mar 2020 23:17:20  ERROR logger.py <module> [ line:21 ] heheheheheheh
Traceback (most recent call last):
  File "D:\Program Files (x86)\python\lib\site-packages\_pytest\config\__init__.py", line 456, in _importconftest
    return self._conftestpath2mod[key]
KeyError: WindowsPath('D:/python/mystudy/AppFramework/TestCases/conftest.py')
 Tue, 03 Mar 2020 23:17:21  INFO conftest.py init_session [ line:65 ] xxxxxxx
 Tue, 03 Mar 2020 23:17:33  WARNING connectionpool.py urlopen [ line:744 ] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionAbortedError(10053, '你的主机中的软件中止了一个已建立的连接。', None, 10053, None))': /wd/hub/session/986ee887-aaf5-4cf1-9cca-90f61ab2acf9/appium/device/current_activity
 Tue, 03 Mar 2020 23:17:34  INFO basepage.py visiable_ele [ line:38 ] 元素('id', 'com.xxzb.fenwoo:id/btn_login')查找成功，耗时0.546370267868042s
 Tue, 03 Mar 2020 23:17:34  INFO test_0_login.py test_prepare [ line:17 ] app已登录,执行数据清空操作!
 Tue, 03 Mar 2020 23:18:20  INFO test_0_login.py test_login_success [ line:25 ] 成功登录
 Tue, 03 Mar 2020 23:18:20  INFO bottom_widget.py switch_bottom_widget [ line:15 ] 切换到页面我
 Tue, 03 Mar 2020 23:18:21  INFO basepage.py visiable_ele [ line:38 ] 元素('-android uiautomator', 'new UiSelector().text("我")')查找成功，耗时0.5664052963256836s
 Tue, 03 Mar 2020 23:18:21  INFO basepage.py get_ele [ line:47 ] 元素('-android uiautomator', 'new UiSelector().text("我")')查找成功！
 Tue, 03 Mar 2020 23:18:22  INFO basepage.py click_ele [ line:80 ] 元素('-android uiautomator', 'new UiSelector().text("我")')成功点击!
