 Wed, 04 Mar 2020 21:40:19  INFO logger.py <module> [ line:20 ] hehehehe
 Wed, 04 Mar 2020 21:40:19  ERROR logger.py <module> [ line:21 ] heheheheheheh
Traceback (most recent call last):
  File "D:\Program Files (x86)\python\lib\site-packages\_pytest\config\__init__.py", line 456, in _importconftest
    return self._conftestpath2mod[key]
KeyError: WindowsPath('D:/python/mystudy/AppFramework/TestCases/conftest.py')
 Wed, 04 Mar 2020 21:40:19  INFO conftest.py init_session [ line:65 ] xxxxxxx
 Wed, 04 Mar 2020 21:40:33  INFO bottom_widget.py switch_bottom_widget [ line:15 ] 切换到页面我
 Wed, 04 Mar 2020 21:40:34  INFO basepage.py visiable_ele [ line:38 ] 元素('-android uiautomator', 'new UiSelector().text("我")')查找成功，耗时0.9847824573516846s
 Wed, 04 Mar 2020 21:40:34  INFO basepage.py get_ele [ line:47 ] 元素('-android uiautomator', 'new UiSelector().text("我")')查找成功！
 Wed, 04 Mar 2020 21:40:35  INFO basepage.py click_ele [ line:93 ] 元素('-android uiautomator', 'new UiSelector().text("我")')成功点击!
 Wed, 04 Mar 2020 21:40:56  INFO basepage.py imgs_screenshot [ line:118 ] 截图成功，文件为D:\python\mystudy\AppFramework\Outputs\Screen_Shots\测试准备,确认app是否已登录-2020-03-04-21-40-55.png
 Wed, 04 Mar 2020 21:40:56  ERROR basepage.py visiable_ele [ line:41 ] 元素('id', 'com.xxzb.fenwoo:id/btn_login')未找到
Traceback (most recent call last):
  File "d:\python\mystudy\AppFramework\Common\basepage.py", line 36, in visiable_ele
    WebDriverWait(self.driver,timeout=20,poll_frequency=0.5).until(EC.visibility_of_element_located(loc))
  File "D:\Program Files (x86)\python\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

 Wed, 04 Mar 2020 21:40:56  INFO test_0_login.py test_prepare [ line:22 ] app已登录,执行数据清空操作!
 Wed, 04 Mar 2020 21:41:22  INFO test_0_login.py test_login_success [ line:48 ] 成功登录用例
 Wed, 04 Mar 2020 21:41:22  INFO bottom_widget.py switch_bottom_widget [ line:15 ] 切换到页面我
 Wed, 04 Mar 2020 21:41:23  INFO basepage.py visiable_ele [ line:38 ] 元素('-android uiautomator', 'new UiSelector().text("我")')查找成功，耗时1.3969156742095947s
 Wed, 04 Mar 2020 21:41:23  INFO basepage.py get_ele [ line:47 ] 元素('-android uiautomator', 'new UiSelector().text("我")')查找成功！
 Wed, 04 Mar 2020 21:41:24  INFO basepage.py click_ele [ line:93 ] 元素('-android uiautomator', 'new UiSelector().text("我")')成功点击!
 Wed, 04 Mar 2020 21:41:26  INFO basepage.py visiable_ele [ line:38 ] 元素('id', 'com.xxzb.fenwoo:id/et_phone')查找成功，耗时1.929178237915039s
 Wed, 04 Mar 2020 21:41:26  INFO basepage.py get_ele [ line:47 ] 元素('id', 'com.xxzb.fenwoo:id/et_phone')查找成功！
 Wed, 04 Mar 2020 21:41:26  INFO basepage.py input_ele_text [ line:72 ] 元素('id', 'com.xxzb.fenwoo:id/et_phone')成功输入18684720553
 Wed, 04 Mar 2020 21:41:27  INFO basepage.py get_ele [ line:47 ] 元素('id', 'com.xxzb.fenwoo:id/btn_next_step')查找成功！
 Wed, 04 Mar 2020 21:41:27  INFO basepage.py click_ele [ line:93 ] 元素('id', 'com.xxzb.fenwoo:id/btn_next_step')成功点击!
 Wed, 04 Mar 2020 21:41:29  INFO basepage.py visiable_ele [ line:38 ] 元素('id', 'com.xxzb.fenwoo:id/et_pwd')查找成功，耗时1.8242268562316895s
 Wed, 04 Mar 2020 21:41:29  INFO basepage.py get_ele [ line:47 ] 元素('id', 'com.xxzb.fenwoo:id/et_pwd')查找成功！
 Wed, 04 Mar 2020 21:41:29  INFO basepage.py input_ele_text [ line:72 ] 元素('id', 'com.xxzb.fenwoo:id/et_pwd')成功输入python
 Wed, 04 Mar 2020 21:41:30  INFO basepage.py get_ele [ line:47 ] 元素('id', 'com.xxzb.fenwoo:id/btn_next_step')查找成功！
 Wed, 04 Mar 2020 21:41:30  INFO basepage.py click_ele [ line:93 ] 元素('id', 'com.xxzb.fenwoo:id/btn_next_step')成功点击!
 Wed, 04 Mar 2020 21:41:32  INFO basepage.py imgs_screenshot [ line:118 ] 截图成功，文件为D:\python\mystudy\AppFramework\Outputs\Screen_Shots\成功登录-2020-03-04-21-41-31.png
 Wed, 04 Mar 2020 21:41:32  ERROR basepage.py get_ele [ line:51 ] 元素('id', 'com.xxzb.fenwoo:id/btn_cancel')查找失败！
Traceback (most recent call last):
  File "d:\python\mystudy\AppFramework\Common\basepage.py", line 46, in get_ele
    ele = self.driver.find_element(*loc)
  File "D:\Program Files (x86)\python\lib\site-packages\appium\webdriver\webdriver.py", line 282, in find_element
    return self.execute(RemoteCommand.FIND_ELEMENT, {
  File "D:\Program Files (x86)\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "D:\Program Files (x86)\python\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "D:\Program Files (x86)\python\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "D:\Program Files (x86)\python\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: An element could not be located on the page using the given search parameters.

