 Thu, 05 Mar 2020 13:54:25  INFO logger.py <module> [ line:20 ] hehehehe
 Thu, 05 Mar 2020 13:54:25  ERROR logger.py <module> [ line:21 ] heheheheheheh
Traceback (most recent call last):
  File "D:\Program Files (x86)\python\lib\site-packages\_pytest\config\__init__.py", line 456, in _importconftest
    return self._conftestpath2mod[key]
KeyError: WindowsPath('D:/python/mystudy/AppFramework/TestCases/conftest.py')
 Thu, 05 Mar 2020 13:54:25  INFO conftest.py init_session [ line:65 ] xxxxxxx
 Thu, 05 Mar 2020 13:54:41  INFO bottom_widget.py switch_bottom_widget [ line:15 ] 切换到页面首页
 Thu, 05 Mar 2020 13:54:41  INFO basepage.py visiable_ele [ line:38 ] 元素('-android uiautomator', 'new UiSelector().text("首页")')查找成功，耗时0.7320003509521484s
 Thu, 05 Mar 2020 13:54:42  INFO basepage.py visiable_ele [ line:38 ] 元素('-android uiautomator', 'new UiSelector().text("首页")')查找成功，耗时0.08881568908691406s
 Thu, 05 Mar 2020 13:54:42  INFO basepage.py get_ele [ line:56 ] 元素('-android uiautomator', 'new UiSelector().text("首页")')查找成功！
 Thu, 05 Mar 2020 13:54:42  INFO basepage.py click_ele [ line:102 ] 元素('-android uiautomator', 'new UiSelector().text("首页")')成功点击!
 Thu, 05 Mar 2020 13:54:44  INFO test_2_invest.py test_invest_worng [ line:51 ] app处于未登录状态,进行账号登录!
 Thu, 05 Mar 2020 13:54:44  INFO test_2_invest.py prepare_login [ line:20 ] 前提:登录状态
 Thu, 05 Mar 2020 13:54:44  INFO bottom_widget.py switch_bottom_widget [ line:15 ] 切换到页面我
 Thu, 05 Mar 2020 13:54:44  INFO basepage.py visiable_ele [ line:38 ] 元素('-android uiautomator', 'new UiSelector().text("我")')查找成功，耗时0.07124853134155273s
 Thu, 05 Mar 2020 13:54:44  INFO basepage.py visiable_ele [ line:38 ] 元素('-android uiautomator', 'new UiSelector().text("我")')查找成功，耗时0.0780789852142334s
 Thu, 05 Mar 2020 13:54:44  INFO basepage.py get_ele [ line:56 ] 元素('-android uiautomator', 'new UiSelector().text("我")')查找成功！
 Thu, 05 Mar 2020 13:54:45  INFO basepage.py click_ele [ line:102 ] 元素('-android uiautomator', 'new UiSelector().text("我")')成功点击!
 Thu, 05 Mar 2020 13:54:47  INFO basepage.py visiable_ele [ line:38 ] 元素('id', 'com.xxzb.fenwoo:id/et_phone')查找成功，耗时1.696359634399414s
 Thu, 05 Mar 2020 13:54:47  INFO basepage.py visiable_ele [ line:38 ] 元素('id', 'com.xxzb.fenwoo:id/et_phone')查找成功，耗时0.07417845726013184s
 Thu, 05 Mar 2020 13:54:47  INFO basepage.py get_ele [ line:56 ] 元素('id', 'com.xxzb.fenwoo:id/et_phone')查找成功！
 Thu, 05 Mar 2020 13:54:48  INFO basepage.py input_ele_text [ line:81 ] 元素('id', 'com.xxzb.fenwoo:id/et_phone')成功输入18684720553
 Thu, 05 Mar 2020 13:54:49  INFO basepage.py visiable_ele [ line:38 ] 元素('id', 'com.xxzb.fenwoo:id/btn_next_step')查找成功，耗时0.8763768672943115s
 Thu, 05 Mar 2020 13:54:49  INFO basepage.py get_ele [ line:56 ] 元素('id', 'com.xxzb.fenwoo:id/btn_next_step')查找成功！
 Thu, 05 Mar 2020 13:54:49  INFO basepage.py click_ele [ line:102 ] 元素('id', 'com.xxzb.fenwoo:id/btn_next_step')成功点击!
 Thu, 05 Mar 2020 13:54:51  INFO basepage.py visiable_ele [ line:38 ] 元素('id', 'com.xxzb.fenwoo:id/et_pwd')查找成功，耗时2.144521713256836s
 Thu, 05 Mar 2020 13:54:51  INFO basepage.py visiable_ele [ line:38 ] 元素('id', 'com.xxzb.fenwoo:id/et_pwd')查找成功，耗时0.060512542724609375s
 Thu, 05 Mar 2020 13:54:51  INFO basepage.py get_ele [ line:56 ] 元素('id', 'com.xxzb.fenwoo:id/et_pwd')查找成功！
 Thu, 05 Mar 2020 13:54:53  INFO basepage.py input_ele_text [ line:81 ] 元素('id', 'com.xxzb.fenwoo:id/et_pwd')成功输入python
 Thu, 05 Mar 2020 13:54:54  INFO basepage.py visiable_ele [ line:38 ] 元素('id', 'com.xxzb.fenwoo:id/btn_next_step')查找成功，耗时1.087752103805542s
 Thu, 05 Mar 2020 13:54:54  INFO basepage.py get_ele [ line:56 ] 元素('id', 'com.xxzb.fenwoo:id/btn_next_step')查找成功！
 Thu, 05 Mar 2020 13:54:54  INFO basepage.py click_ele [ line:102 ] 元素('id', 'com.xxzb.fenwoo:id/btn_next_step')成功点击!
 Thu, 05 Mar 2020 13:55:02  INFO bottom_widget.py switch_bottom_widget [ line:15 ] 切换到页面首页
 Thu, 05 Mar 2020 13:55:02  INFO basepage.py visiable_ele [ line:38 ] 元素('-android uiautomator', 'new UiSelector().text("首页")')查找成功，耗时0.0985710620880127s
 Thu, 05 Mar 2020 13:55:02  INFO basepage.py visiable_ele [ line:38 ] 元素('-android uiautomator', 'new UiSelector().text("首页")')查找成功，耗时0.06148886680603027s
 Thu, 05 Mar 2020 13:55:02  INFO basepage.py get_ele [ line:56 ] 元素('-android uiautomator', 'new UiSelector().text("首页")')查找成功！
 Thu, 05 Mar 2020 13:55:03  INFO basepage.py click_ele [ line:102 ] 元素('-android uiautomator', 'new UiSelector().text("首页")')成功点击!
 Thu, 05 Mar 2020 13:55:05  INFO test_2_invest.py prepare_login [ line:30 ] 确认登录成功!
 Thu, 05 Mar 2020 13:55:05  INFO bottom_widget.py switch_bottom_widget [ line:15 ] 切换到页面项目
 Thu, 05 Mar 2020 13:55:05  INFO basepage.py visiable_ele [ line:38 ] 元素('-android uiautomator', 'new UiSelector().text("项目")')查找成功，耗时0.0771036148071289s
 Thu, 05 Mar 2020 13:55:05  INFO basepage.py visiable_ele [ line:38 ] 元素('-android uiautomator', 'new UiSelector().text("项目")')查找成功，耗时0.06102347373962402s
 Thu, 05 Mar 2020 13:55:06  INFO basepage.py get_ele [ line:56 ] 元素('-android uiautomator', 'new UiSelector().text("项目")')查找成功！
 Thu, 05 Mar 2020 13:55:06  ERROR basepage.py imgs_screenshot [ line:129 ] 截图失败!
Traceback (most recent call last):
  File "d:\python\mystudy\AppFramework\Common\basepage.py", line 101, in click_ele
    ele.click()
  File "D:\Program Files (x86)\python\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "D:\Program Files (x86)\python\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "D:\Program Files (x86)\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "D:\Program Files (x86)\python\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "D:\Program Files (x86)\python\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "D:\Program Files (x86)\python\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\python\mystudy\AppFramework\Common\basepage.py", line 126, in imgs_screenshot
    self.driver.save_screenshot(pic_path)
  File "D:\Program Files (x86)\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1055, in save_screenshot
    return self.get_screenshot_as_file(filename)
  File "D:\Program Files (x86)\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1032, in get_screenshot_as_file
    png = self.get_screenshot_as_png()
  File "D:\Program Files (x86)\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1064, in get_screenshot_as_png
    return base64.b64decode(self.get_screenshot_as_base64().encode('ascii'))
  File "D:\Program Files (x86)\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1074, in get_screenshot_as_base64
    return self.execute(Command.SCREENSHOT)['value']
  File "D:\Program Files (x86)\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "D:\Program Files (x86)\python\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "D:\Program Files (x86)\python\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "D:\Program Files (x86)\python\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up

