 Tue, 03 Mar 2020 22:41:59  INFO logger.py <module> [ line:20 ] hehehehe
 Tue, 03 Mar 2020 22:41:59  ERROR logger.py <module> [ line:21 ] heheheheheheh
Traceback (most recent call last):
  File "D:\Program Files (x86)\python\lib\site-packages\_pytest\config\__init__.py", line 456, in _importconftest
    return self._conftestpath2mod[key]
KeyError: WindowsPath('D:/python/mystudy/AppFramework/TestCases/conftest.py')
 Tue, 03 Mar 2020 22:41:59  INFO conftest.py init_session [ line:61 ] xxxxxxx
