 Wed, 04 Mar 2020 13:01:54  INFO logger.py <module> [ line:20 ] hehehehe
 Wed, 04 Mar 2020 13:01:54  ERROR logger.py <module> [ line:21 ] heheheheheheh
Traceback (most recent call last):
  File "D:\Program Files (x86)\python\lib\site-packages\_pytest\config\__init__.py", line 456, in _importconftest
    return self._conftestpath2mod[key]
KeyError: WindowsPath('D:/python/mystudy/AppFramework/TestCases/conftest.py')
 Wed, 04 Mar 2020 13:01:54  INFO conftest.py init_session [ line:65 ] xxxxxxx
 Wed, 04 Mar 2020 13:02:08  WARNING connectionpool.py urlopen [ line:744 ] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /wd/hub/session/9871b699-0363-4c28-a826-6fc9c5976ad6/appium/device/current_activity
 Wed, 04 Mar 2020 13:02:09  INFO basepage.py visiable_ele [ line:38 ] 元素('id', 'com.xxzb.fenwoo:id/btn_login')查找成功，耗时0.5394413471221924s
 Wed, 04 Mar 2020 13:02:09  INFO test_0_login.py test_prepare [ line:19 ] app已登录,执行数据清空操作!
 Wed, 04 Mar 2020 13:02:56  INFO test_0_login.py test_login_tele_wrong [ line:27 ] 手机号输入错误用例
 Wed, 04 Mar 2020 13:02:56  INFO bottom_widget.py switch_bottom_widget [ line:15 ] 切换到页面我
 Wed, 04 Mar 2020 13:02:57  INFO basepage.py visiable_ele [ line:38 ] 元素('-android uiautomator', 'new UiSelector().text("我")')查找成功，耗时0.5700273513793945s
 Wed, 04 Mar 2020 13:02:57  INFO basepage.py get_ele [ line:47 ] 元素('-android uiautomator', 'new UiSelector().text("我")')查找成功！
 Wed, 04 Mar 2020 13:02:58  INFO basepage.py click_ele [ line:80 ] 元素('-android uiautomator', 'new UiSelector().text("我")')成功点击!
