 Wed, 04 Mar 2020 18:23:57  INFO logger.py <module> [ line:20 ] hehehehe
 Wed, 04 Mar 2020 18:23:57  ERROR logger.py <module> [ line:21 ] heheheheheheh
Traceback (most recent call last):
  File "D:\Program Files (x86)\python\lib\site-packages\_pytest\config\__init__.py", line 456, in _importconftest
    return self._conftestpath2mod[key]
KeyError: WindowsPath('D:/python/mystudy/AppFramework/TestCases/conftest.py')
 Wed, 04 Mar 2020 18:23:57  INFO conftest.py init_session [ line:65 ] xxxxxxx
